# Generated by Django 3.2.9 on 2022-03-27 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceid', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('csv', models.FileField(upload_to='csvs/')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('templateid', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('created', models.DateField(null=True)),
                ('modified', models.DateField(null=True)),
                ('template', models.FileField(upload_to='templates/')),
                ('scripts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('templateid', models.CharField(max_length=50)),
                ('sourceid', models.CharField(max_length=50)),
                ('created', models.DateField(null=True)),
                ('modified', models.DateField(null=True)),
                ('widget', models.JSONField(null=True)),
            ],
        ),
    ]
