# Generated by Django 4.0.3 on 2022-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(),
        ),
    ]
