# Generated by Django 3.2.9 on 2022-03-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0002_alter_template_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='csv',
        ),
        migrations.AddField(
            model_name='datasource',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
