# Generated by Django 3.2.9 on 2022-04-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0003_auto_20220327_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='metadata',
            field=models.TextField(null=True),
        ),
    ]
