# Generated by Django 3.2.9 on 2022-04-02 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0004_datasource_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widgetid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
