# Generated by Django 3.2.9 on 2022-04-10 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0005_widget_widgetid'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionid', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('sourceid', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100, null=True)),
                ('parameters', models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
