# Generated by Django 3.2.9 on 2022-04-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0006_auto_20220410_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconnection',
            name='resultobject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
