# Generated by Django 3.2.9 on 2022-05-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0008_auto_20220528_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='runtimeFilterDefs',
            field=models.JSONField(null=True),
        ),
    ]
