# Generated by Django 3.2.9 on 2022-05-29 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0009_widget_runtimefilterdefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dashboardid', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('widgets', models.JSONField(null=True)),
            ],
        ),
    ]
