# Generated by Django 3.2.9 on 2022-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0010_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='modified',
            field=models.DateField(null=True),
        ),
    ]
