# Generated by Django 3.2.9 on 2022-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0012_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='left',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='top',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
