# Generated by Django 3.2.9 on 2022-06-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowfinintegration', '0013_auto_20220611_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='left',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='top',
        ),
    ]
